name: bayesiandrape_nb_mpi
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.2
  - geopandas
  - ordered-set
  - rioxarray
  - shapely
  - emcee
  - corner
  - scipy
  - pytorch
  - nb_conda
  - ucx
  - mpich

