name: bayesiandrape2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.2
  - geopandas
  - ordered-set
  - rioxarray
  - shapely
  - scipy
  - pytorch
  - pytest
  - jupyter
